### ISSUE TITLE
Standardize the .travis.yml files?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#41]
So, I finally wrote a quick and dirty scanner for all the fxa-* repos' .travis.yml files:

```js
var Wreck = require('wreck')

var repos = [
  'mozilla/fxa-auth-db-mem',
  'mozilla/fxa-auth-db-mysql',
  'mozilla/fxa-auth-db-server',
  'mozilla/fxa-auth-mailer',
  'mozilla/fxa-auth-server',
  'mozilla/fxa-basket-proxy',
  'mozilla/fxa-content-experiments',
  'mozilla/fxa-content-server',
  'mozilla/fxa-content-server-l10n',
  'mozilla/fxa-deployment',
  'mozilla/fxa-dev',
  'mozilla/fxa-easter-egg',
  'mozilla/fxa-js-client',
  'mozilla/fxa-jwtool',
  'mozilla/fxa-local-dev',
  'mozilla/fxa-notification-server',
  'mozilla/fxa-oauth-console',
  'mozilla/fxa-oauth-server',
  'mozilla/fxa-password-strength-checker',
  'mozilla/fxa-profile-server',
  'mozilla/fxa-relier-client',
  'mozilla/fxa-scrypt-helper',
  'mozilla/hapi-fxa-oauth'
]

repos.forEach(function (repo) {
  Wreck.get(getTravisYaml(repo), function (err, res, payload) {
    console.log('# %s\n%s\n\n', repo, payload)
  })
})

function getTravisYaml(repo) {
  return 'https://raw.githubusercontent.com/' + repo + '/master/.travis.yml'
}
```

And here's a [somewhat heavily] edited version of the output for each of the repos:

1. ### mozilla/fxa-auth-mailer
    ```yaml
language: node_js

node_js:
 - "0.10"
```

1. ### mozilla/fxa-auth-db-mem
    ```yaml
language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"

before_install:
  - npm config set spin false
```

1. ### mozilla/fxa-auth-db-mysql
    ```yaml
language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"

before_install:
  - npm install -g npm@2
```

1. ### mozilla/fxa-auth-db-server
    ```yaml
language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"
```

1. ### mozilla/fxa-auth-server
    ```yaml
language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"

sudo: false
```

1. ### mozilla/fxa-content-experiments
    ```yaml
language: node_js

sudo: false

node_js:
  - "0.10"
```

1. ### mozilla/fxa-content-server
    ```yaml
language: node_js

node_js:
  - "0.10"
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - app/bower_components
    - fxa-auth-server/node_modules

before_install:
  - npm install -g npm@2
```

1. ### mozilla/fxa-js-client
    ```yaml
language: node_js

sudo: false

node_js:
  - "0.10"
```

1. ### mozilla/fxa-easter-egg
    ```yaml
language: node_js

node_js:
  - "0.10"
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components
```

1. ### mozilla/fxa-local-dev
    ```yaml
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - npm install -g npm@2.4
```

1. ### mozilla/fxa-notification-server
    ```yaml
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

sudo: false
```

1. ### mozilla/fxa-oauth-console
    ```yaml
language: node_js

node_js:
  - '0.10'
```

1. ### mozilla/fxa-oauth-server
    ```yaml
language: node_js

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

sudo: false

before_install:
  - npm install -g npm@2
```

1. ### mozilla/fxa-password-strength-checker
    ```yaml
language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm install -g npm@2
```

1. ### mozilla/fxa-profile-server
    ```yaml
language: node_js

node_js:
  - '0.10'
  - '0.12'
  - iojs

before_install:
  - npm install -g npm@2
```

1. ### mozilla/fxa-relier-client
    ```yaml
language: node_js

sudo: false

node_js:
  - "0.10"
```

---

#### The following repos didn't have a /.travis.yml file in the repo:

- mozilla/fxa-basket-proxy
- mozilla/fxa-content-server-l10n
- mozilla/fxa-deployment
- mozilla/fxa-dev
- mozilla/fxa-jwtool
- mozilla/fxa-scrypt-helper
- mozilla/hapi-fxa-oauth
