### ISSUE TITLE
[RTL] The radio header for disconnecting a client is aligned to the left, should be to the right [bz1617720]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4262]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617720

Created attachment 9128594
Screenshot

See attached, the second paragraph should be aligned to the right.

Adding this code should fix this:
```css
html[dir="rtl"] #client-disconnect .radio-header {
  text-align: right;
}
```
Though, I couldn't find where the source code files are at...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1196)
┆Issue Number: FXA-1196
