### ISSUE TITLE
[RTL] Wrong padding for the firefox family services section on the sign up page [bz1617725]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4263]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617725

Created attachment 9128602
Before

See before/after screenshots.

Relevant code to add:
```css
html[dir="rtl"] .sign-up > .firefox-family-services {
  margin: 90px 36px 0 0;
}

html[dir="rtl"] .firefox-family-services > ul > .firefox-service .logo.logo-lockwise {
  background-position-x: 5px;
}

html[dir="rtl"] .firefox-family-services > ul > .firefox-service .logo.logo-monitor {
  background-position-x: 12px;
}

html[dir="rtl"] .firefox-family-services > ul > .firefox-service .logo.logo-send {
  background-position-x: 8px;
}

html[dir="rtl"] .firefox-family-services > ul > .firefox-service {
  padding: 0 0 20px 10px;
}
```

Code to remove, seems to be a leftover:
```css
html[dir="rtl"] .firefox-family-services > h2 {
  padding-right: 10px;
}
```

As a side bonus, add this rule:
```css
html[dir="rtl"] .input-row input:not([type="number"]) {
  direction: ltr;
}
```
... and remove the `direction: ltr` from the `html[dir="rtl"] .input-row input` rule (this is so the question mark of the "How old are you?" field won't appear in reverse).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1197)
┆Issue Number: FXA-1197
